Pagination added to index.php
catsandspace/blog pull request #113
Opened 2016-12-03 11:54 UTC by aalselius

index.php - Pagination added at bottom, currently set to 2 a page for testing purpose
 - comment-bubble for comments=0

2016-12-03 17:20 UTC, LJNGDAHL requested changes
@aalselius: Snyggt jobbat! Försökte nu vara lite bättre på att förstå allt som sker, så har lämnat några förslag på förändringar på sådana saker som jag upptäckte. Du kan väl kika på det? Annars: topp! Du får gärna berätta lite mer när vi ses.

2016-12-03 17:20 UTC, LJNGDAHL commented on index.php
> +    }
Här borde vi ha någon else va? Om vår query inte funkar.

2016-12-03 17:20 UTC, LJNGDAHL commented on index.php
> +    <div class="pagination-text">
@aalselius: om vi döper enligt BEM, så borde den inre div-klassen heta _pagination-wrapper__text_.

2016-12-03 17:20 UTC, LJNGDAHL commented on styles/scss/_utilities.scss
> +.pagination-text {
Döp om till _pagination-wrapper__text_. Alternativt, om du inte lägger på någon styling på _pagination-wrapper_, kanske vi kan ta bort den klassen och den div:en?

2016-12-03 17:20 UTC, LJNGDAHL commented on index.php
>                          endwhile;
Indenteringen ser lite konstig ut här, men det kanske bara är github som spökar.

2016-12-03 17:54 UTC, aalselius commented on index.php
> +    }
Självklart!

2016-12-03 17:55 UTC, aalselius commented on index.php
>                          endwhile;
Det är nog jag som tyckte det blev mer lättläst. Vi kan titta på detta på tisdag.

2016-12-03 17:56 UTC, aalselius commented on styles/scss/_utilities.scss
> +.pagination-text {
Jag är glad att jag fick styling överhuvudtaget.
Vi tittar vidare på detta på tisdag.

2016-12-03 17:57 UTC, aalselius commented on index.php
> +    <div class="pagination-text">
Jag ska läsa din länk i morgon...

2016-12-03 17:58 UTC, LJNGDAHL commented on index.php
>                          endwhile;
@aalselius: äsch, låt det vara! Jag tror att det är github som spökar.

2016-12-03 17:59 UTC, LJNGDAHL commented on styles/scss/_utilities.scss
> +.pagination-text {
@aalselius: det gör vi! Kanske dags att sätta oss snart och gå igenom/rensa upp. Om du vill kan ju du vara huvudansvarig för det (samt för att anpassa för desktop/tablet). Jag sitter gärna med om du vill ha någon att bolla med.

2016-12-03 18:00 UTC, LJNGDAHL commented
PS! Tummen upp att merge:a när du vill från mitt håll!

2016-12-06 08:49 UTC, LJNGDAHL approved these changes

2016-12-06 10:34 UTC, merged